# Your Solution

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: mohanmain.azurecr.io/catalog:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: "DATABASE_URL"
              value: "postgresql://mohandb_user:qb4uIrvAnoWQl6nBLPE4BqDCBr1BctOS@dpg-crlc3cbtq21c73ec93f0-a.oregon-postgres.render.com/mohandb"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: mohanmain.azurecr.io/inventory:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: "DATABASE_URL"
              value: "postgresql://mohandb_user:qb4uIrvAnoWQl6nBLPE4BqDCBr1BctOS@dpg-crlc3cbtq21c73ec93f0-a.oregon-postgres.render.com/mohandb"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: book-catalog

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: inventory-management
